<?php

/**
 *
 * Autogenerated with this command
 *
 * php phreak make:a phreak-cmd @commandname
 *
 */

namespace App\Commands;

use Log;
use Illuminate\Console\Scheduling\Schedule;
use LaravelZero\Framework\Commands\Command;

use App\Commands\Phreaks\TUI;

class @commandname extends Command
{
    /**
     * The signature of @commandname.
     *
     * @var string
     */
    protected $signature = 'command:name
                            {argOne? : Argument Description Goes Here}
                            {--O|option= : Option Description Goes Here}';

    /**
     * The description of @commandname.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        // $cmds    = $this->option();
        // $argOne  = $this->argument('argOne');
        //
    }

    /**
     * Define the command's schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule $schedule
     * @return void
     */
    public function schedule(Schedule $schedule): void
    {
        // $schedule->command(static::class)->everyMinute();
    }
}
